### ISSUE TITLE
sigma isn't a miner

### ISSUE THREAD

**Issue by Panky55** [owersite/sigma-wiper#4]
so port 3000 is local host retard and there isn't full on proof

**Comment by owersite** [comment]
It's been shown in past that Sigma actually uses PC for mining, after getting exposed they laid low and they are since then. There could potentially be a miner inside still and this is just clearing all files that have connections with Sigma. I made this repository as a  appreciate to Xatz team for making same one in Java. Do not call me nor anyone retard for that.
